server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
#  main:
#    web-application-type: reactive
  application:
    name: apigateway-service
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: chat-service
#            uri: lb://CHAT-SERVICE
#            predicates:
#              - Path=/chat/*, /*/chat/**
#          - id: websocket_route
#            uri: lb://CHAT-SERVICE
#            predicates:
#              - Path=/ws/**